name: Geoserver base image PROD - deploy (auto)

on:
  push:
    branches:
      - develop

env:
  ECR_REGION: ca-central-1

jobs:
  build:
    if: ${{ false }}  # disable for now
    name: Building Docker Image on runner
    runs-on: [self-hosted, linux, x64, geocentralis-prod]
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.ECR_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: private

    - name: Build and push the image
      id: Build-Docker-Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: internal-images

      run: |
        docker-compose -f docker-compose-build.yml build        
        source .env && docker tag kartoza/geoserver-mod:$GS_VERSION $ECR_REGISTRY/$ECR_REPOSITORY:kartoza-geoserver-mod_$GS_VERSION
        source .env && docker push $ECR_REGISTRY/$ECR_REPOSITORY:kartoza-geoserver-mod_$GS_VERSION
